// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject

package di

import (
	"database/sql"

	"backend-dev-val/internal/handler"
	"backend-dev-val/internal/repository"
	"backend-dev-val/internal/usecase"

	"github.com/gin-gonic/gin"
)

func InitializeApp(db *sql.DB) *gin.Engine {
	todoRepository := repository.NewTodoRepository(db)
	todoUsecase := usecase.NewTodoUsecase(todoRepository)
	todoHandler := handler.NewTodoHandler(todoUsecase)
	engine := handler.SetupRouter(todoHandler)
	return engine
}
